import {
  Activity,
  Airplay,
  AlarmClock,
  Archive,
  Award,
  Backpack,
  Banknote,
  BarChart,
  BatteryFull,
  Bell,
  Bike,
  Bluetooth,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Briefcase,
  Brush,
  Bug,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Castle,
  CheckCircle,
  CheckSquare,
  ChevronRightCircle,
  CircleDollarSign,
  ClipboardList,
  Cloud,
  CloudLightning,
  CloudSun,
  Code,
  Coins,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Cross,
  Crown,
  Database,
  Disc,
  Divide,
  DollarSign,
  Download,
  Droplet,
  Earth,
  Eye,
  Feather,
  FileText,
  Film,
  Fingerprint,
  Flame,
  FlaskConical,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Home,
  Hourglass,
  Image,
  Inbox,
  Infinity,
  Keyboard,
  Landmark,
  Layers,
  Lightbulb,
  LineChart,
  Link,
  ListTodo,
  Loader,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  MousePointer,
  Music,
  Newspaper,
  Palette,
  Paperclip,
  PartyPopper,
  PenTool,
  Phone,
  PieChart,
  Pin,
  Plane,
  Plug,
  Puzzle,
  Rocket,
  Satellite,
  School,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  ThumbsUp,
  Timer,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Video,
  Wallet,
  Wand,
  Watch,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import { IconOption } from "../types/icons";

export const ICONS: IconOption[] = [
  { name: "Activity", icon: Activity },
  { name: "Airplay", icon: Airplay },
  { name: "AlarmClock", icon: AlarmClock },
  { name: "Archive", icon: Archive },
  { name: "Award", icon: Award },
  { name: "Backpack", icon: Backpack },
  { name: "Banknote", icon: Banknote },
  { name: "BarChart", icon: BarChart },
  { name: "BatteryFull", icon: BatteryFull },
  { name: "Bell", icon: Bell },
  { name: "Bike", icon: Bike },
  { name: "Bluetooth", icon: Bluetooth },
  { name: "BookOpen", icon: BookOpen },
  { name: "Bookmark", icon: Bookmark },
  { name: "Bot", icon: Bot },
  { name: "Box", icon: Box },
  { name: "Briefcase", icon: Briefcase },
  { name: "Brush", icon: Brush },
  { name: "Bug", icon: Bug },
  { name: "Cake", icon: Cake },
  { name: "Calculator", icon: Calculator },
  { name: "Calendar", icon: Calendar },
  { name: "Camera", icon: Camera },
  { name: "Car", icon: Car },
  { name: "Castle", icon: Castle },
  { name: "CheckCircle", icon: CheckCircle },
  { name: "CheckSquare", icon: CheckSquare },
  { name: "ChevronRightCircle", icon: ChevronRightCircle },
  { name: "CircleDollarSign", icon: CircleDollarSign },
  { name: "ClipboardList", icon: ClipboardList },
  { name: "Cloud", icon: Cloud },
  { name: "CloudLightning", icon: CloudLightning },
  { name: "CloudSun", icon: CloudSun },
  { name: "Code", icon: Code },
  { name: "Coins", icon: Coins },
  { name: "Compass", icon: Compass },
  { name: "Contact", icon: Contact },
  { name: "Cpu", icon: Cpu },
  { name: "CreditCard", icon: CreditCard },
  { name: "Cross", icon: Cross },
  { name: "Crown", icon: Crown },
  { name: "Database", icon: Database },
  { name: "Disc", icon: Disc },
  { name: "Divide", icon: Divide },
  { name: "DollarSign", icon: DollarSign },
  { name: "Download", icon: Download },
  { name: "Droplet", icon: Droplet },
  { name: "Earth", icon: Earth },
  { name: "Eye", icon: Eye },
  { name: "Feather", icon: Feather },
  { name: "FileText", icon: FileText },
  { name: "Film", icon: Film },
  { name: "Fingerprint", icon: Fingerprint },
  { name: "Flame", icon: Flame },
  { name: "FlaskConical", icon: FlaskConical },
  { name: "Folder", icon: Folder },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Gauge", icon: Gauge },
  { name: "Gem", icon: Gem },
  { name: "Ghost", icon: Ghost },
  { name: "Globe", icon: Globe },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "Hammer", icon: Hammer },
  { name: "Handshake", icon: Handshake },
  { name: "HardDrive", icon: HardDrive },
  { name: "Hash", icon: Hash },
  { name: "Headphones", icon: Headphones },
  { name: "Heart", icon: Heart },
  { name: "Home", icon: Home },
  { name: "Hourglass", icon: Hourglass },
  { name: "Image", icon: Image },
  { name: "Inbox", icon: Inbox },
  { name: "Infinity", icon: Infinity },
  { name: "Keyboard", icon: Keyboard },
  { name: "Landmark", icon: Landmark },
  { name: "Layers", icon: Layers },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "LineChart", icon: LineChart },
  { name: "Link", icon: Link },
  { name: "ListTodo", icon: ListTodo },
  { name: "Loader", icon: Loader },
  { name: "Lock", icon: Lock },
  { name: "Mail", icon: Mail },
  { name: "Map", icon: Map },
  { name: "Megaphone", icon: Megaphone },
  { name: "MessageCircle", icon: MessageCircle },
  { name: "Mic", icon: Mic },
  { name: "Monitor", icon: Monitor },
  { name: "Moon", icon: Moon },
  { name: "MousePointer", icon: MousePointer },
  { name: "Music", icon: Music },
  { name: "Newspaper", icon: Newspaper },
  { name: "Palette", icon: Palette },
  { name: "Paperclip", icon: Paperclip },
  { name: "PartyPopper", icon: PartyPopper },
  { name: "PenTool", icon: PenTool },
  { name: "Phone", icon: Phone },
  { name: "PieChart", icon: PieChart },
  { name: "Pin", icon: Pin },
  { name: "Plane", icon: Plane },
  { name: "Plug", icon: Plug },
  { name: "Puzzle", icon: Puzzle },
  { name: "Rocket", icon: Rocket },
  { name: "Satellite", icon: Satellite },
  { name: "School", icon: School },
  { name: "Settings", icon: Settings },
  { name: "ShieldCheck", icon: ShieldCheck },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Sparkles", icon: Sparkles },
  { name: "Star", icon: Star },
  { name: "Sun", icon: Sun },
  { name: "Tag", icon: Tag },
  { name: "Target", icon: Target },
  { name: "ThumbsUp", icon: ThumbsUp },
  { name: "Timer", icon: Timer },
  { name: "Trophy", icon: Trophy },
  { name: "Truck", icon: Truck },
  { name: "Tv", icon: Tv },
  { name: "Umbrella", icon: Umbrella },
  { name: "User", icon: User },
  { name: "Video", icon: Video },
  { name: "Wallet", icon: Wallet },
  { name: "Wand", icon: Wand },
  { name: "Watch", icon: Watch },
  { name: "Wifi", icon: Wifi },
  { name: "Wrench", icon: Wrench },
  { name: "Zap", icon: Zap },
];
