import {
  Activity,
  Airplay,
  AlarmClock,
  Archive,
  Award,
  Backpack,
  Banknote,
  BarChart,
  BatteryFull,
  Bell,
  Bike,
  Bluetooth,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Briefcase,
  Brush,
  Bug,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Castle,
  CheckCircle,
  CheckSquare,
  ChevronRightCircle,
  CircleDollarSign,
  ClipboardList,
  Cloud,
  CloudLightning,
  CloudSun,
  Code,
  Coins,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Cross,
  Crown,
  Database,
  Disc,
  Divide,
  DollarSign,
  Download,
  Droplet,
  Earth,
  Eye,
  Feather,
  FileText,
  Film,
  Fingerprint,
  Flame,
  FlaskConical,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Home,
  Hourglass,
  Image,
  Inbox,
  Infinity,
  Keyboard,
  Landmark,
  Layers,
  Lightbulb,
  LineChart,
  Link,
  ListTodo,
  Loader,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  MousePointer,
  Music,
  Newspaper,
  Palette,
  Paperclip,
  PartyPopper,
  PenTool,
  Phone,
  PieChart,
  Pin,
  Plane,
  Plug,
  Puzzle,
  Rocket,
  Satellite,
  School,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  ThumbsUp,
  Timer,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Video,
  Wallet,
  Wand,
  Watch,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import { NameValueIconObj } from "../types/icons";

export const ICONS: NameValueIconObj[] = [
  { name: "Activity", value: Activity },
  { name: "Airplay", value: Airplay },
  { name: "Alarm Clock", value: AlarmClock },
  { name: "Archive", value: Archive },
  { name: "Award", value: Award },
  { name: "Backpack", value: Backpack },
  { name: "Banknote", value: Banknote },
  { name: "Bar Chart", value: BarChart },
  { name: "Battery Full", value: BatteryFull },
  { name: "Bell", value: Bell },
  { name: "Bike", value: Bike },
  { name: "Bluetooth", value: Bluetooth },
  { name: "Book Open", value: BookOpen },
  { name: "Bookmark", value: Bookmark },
  { name: "Bot", value: Bot },
  { name: "Box", value: Box },
  { name: "Briefcase", value: Briefcase },
  { name: "Brush", value: Brush },
  { name: "Bug", value: Bug },
  { name: "Cake", value: Cake },
  { name: "Calculator", value: Calculator },
  { name: "Calendar", value: Calendar },
  { name: "Camera", value: Camera },
  { name: "Car", value: Car },
  { name: "Castle", value: Castle },
  { name: "Check Circle", value: CheckCircle },
  { name: "Check Square", value: CheckSquare },
  { name: "Chevron Right Circle", value: ChevronRightCircle },
  { name: "Circle Dollar Sign", value: CircleDollarSign },
  { name: "Clipboard List", value: ClipboardList },
  { name: "Cloud", value: Cloud },
  { name: "Cloud Lightning", value: CloudLightning },
  { name: "Cloud Sun", value: CloudSun },
  { name: "Code", value: Code },
  { name: "Coins", value: Coins },
  { name: "Compass", value: Compass },
  { name: "Contact", value: Contact },
  { name: "Cpu", value: Cpu },
  { name: "Credit Card", value: CreditCard },
  { name: "Cross", value: Cross },
  { name: "Crown", value: Crown },
  { name: "Database", value: Database },
  { name: "Disc", value: Disc },
  { name: "Divide", value: Divide },
  { name: "Dollar Sign", value: DollarSign },
  { name: "Download", value: Download },
  { name: "Droplet", value: Droplet },
  { name: "Earth", value: Earth },
  { name: "Eye", value: Eye },
  { name: "Feather", value: Feather },
  { name: "File Text", value: FileText },
  { name: "Film", value: Film },
  { name: "Fingerprint", value: Fingerprint },
  { name: "Flame", value: Flame },
  { name: "Flask Conical", value: FlaskConical },
  { name: "Folder", value: Folder },
  { name: "Gamepad 2", value: Gamepad2 },
  { name: "Gauge", value: Gauge },
  { name: "Gem", value: Gem },
  { name: "Ghost", value: Ghost },
  { name: "Globe", value: Globe },
  { name: "Graduation Cap", value: GraduationCap },
  { name: "Hammer", value: Hammer },
  { name: "Handshake", value: Handshake },
  { name: "Hard Drive", value: HardDrive },
  { name: "Hash", value: Hash },
  { name: "Headphones", value: Headphones },
  { name: "Heart", value: Heart },
  { name: "Home", value: Home },
  { name: "Hourglass", value: Hourglass },
  { name: "Image", value: Image },
  { name: "Inbox", value: Inbox },
  { name: "Infinity", value: Infinity },
  { name: "Keyboard", value: Keyboard },
  { name: "Landmark", value: Landmark },
  { name: "Layers", value: Layers },
  { name: "Lightbulb", value: Lightbulb },
  { name: "Line Chart", value: LineChart },
  { name: "Link", value: Link },
  { name: "List Todo", value: ListTodo },
  { name: "Loader", value: Loader },
  { name: "Lock", value: Lock },
  { name: "Mail", value: Mail },
  { name: "Map", value: Map },
  { name: "Megaphone", value: Megaphone },
  { name: "Message Circle", value: MessageCircle },
  { name: "Mic", value: Mic },
  { name: "Monitor", value: Monitor },
  { name: "Moon", value: Moon },
  { name: "Mouse Pointer", value: MousePointer },
  { name: "Music", value: Music },
  { name: "Newspaper", value: Newspaper },
  { name: "Palette", value: Palette },
  { name: "Paperclip", value: Paperclip },
  { name: "Party Popper", value: PartyPopper },
  { name: "Pen Tool", value: PenTool },
  { name: "Phone", value: Phone },
  { name: "Pie Chart", value: PieChart },
  { name: "Pin", value: Pin },
  { name: "Plane", value: Plane },
  { name: "Plug", value: Plug },
  { name: "Puzzle", value: Puzzle },
  { name: "Rocket", value: Rocket },
  { name: "Satellite", value: Satellite },
  { name: "School", value: School },
  { name: "Settings", value: Settings },
  { name: "Shield Check", value: ShieldCheck },
  { name: "Shopping Cart", value: ShoppingCart },
  { name: "Sparkles", value: Sparkles },
  { name: "Star", value: Star },
  { name: "Sun", value: Sun },
  { name: "Tag", value: Tag },
  { name: "Target", value: Target },
  { name: "Thumbs Up", value: ThumbsUp },
  { name: "Timer", value: Timer },
  { name: "Trophy", value: Trophy },
  { name: "Truck", value: Truck },
  { name: "Tv", value: Tv },
  { name: "Umbrella", value: Umbrella },
  { name: "User", value: User },
  { name: "Video", value: Video },
  { name: "Wallet", value: Wallet },
  { name: "Wand", value: Wand },
  { name: "Watch", value: Watch },
  { name: "Wifi", value: Wifi },
  { name: "Wrench", value: Wrench },
  { name: "Zap", value: Zap },
] as const;

export const ICON_NAMES = ICONS.map((icon) => icon.name);
