import { LucideIcon } from "lucide-react";

export type IconName =
  | "Activity"
  | "Airplay"
  | "Alarm Clock"
  | "Archive"
  | "Award"
  | "Backpack"
  | "Banknote"
  | "Bar Chart"
  | "Battery Full"
  | "Bell"
  | "Bike"
  | "Bluetooth"
  | "Book Open"
  | "Bookmark"
  | "Bot"
  | "Box"
  | "Briefcase"
  | "Brush"
  | "Bug"
  | "Cake"
  | "Calculator"
  | "Calendar"
  | "Camera"
  | "Car"
  | "Castle"
  | "Check Circle"
  | "Check Square"
  | "Chevron Right Circle"
  | "Circle Dollar Sign"
  | "Clipboard List"
  | "Cloud"
  | "Cloud Lightning"
  | "Cloud Sun"
  | "Code"
  | "Coins"
  | "Compass"
  | "Contact"
  | "Cpu"
  | "Credit Card"
  | "Cross"
  | "Crown"
  | "Database"
  | "Disc"
  | "Divide"
  | "Dollar Sign"
  | "Download"
  | "Droplet"
  | "Earth"
  | "Eye"
  | "Feather"
  | "File Text"
  | "Film"
  | "Fingerprint"
  | "Flame"
  | "Flask Conical"
  | "Folder"
  | "Gamepad 2"
  | "Gauge"
  | "Gem"
  | "Ghost"
  | "Globe"
  | "Graduation Cap"
  | "Hammer"
  | "Handshake"
  | "Hard Drive"
  | "Hash"
  | "Headphones"
  | "Heart"
  | "Home"
  | "Hourglass"
  | "Image"
  | "Inbox"
  | "Infinity"
  | "Keyboard"
  | "Landmark"
  | "Layers"
  | "Lightbulb"
  | "Line Chart"
  | "Link"
  | "List Todo"
  | "Loader"
  | "Lock"
  | "Mail"
  | "Map"
  | "Megaphone"
  | "Message Circle"
  | "Mic"
  | "Monitor"
  | "Moon"
  | "Mouse Pointer"
  | "Music"
  | "Newspaper"
  | "Palette"
  | "Paperclip"
  | "Party Popper"
  | "Pen Tool"
  | "Phone"
  | "Pie Chart"
  | "Pin"
  | "Plane"
  | "Plug"
  | "Puzzle"
  | "Rocket"
  | "Satellite"
  | "School"
  | "Settings"
  | "Shield Check"
  | "Shopping Cart"
  | "Sparkles"
  | "Star"
  | "Sun"
  | "Tag"
  | "Target"
  | "Thumbs Up"
  | "Timer"
  | "Trophy"
  | "Truck"
  | "Tv"
  | "Umbrella"
  | "User"
  | "Video"
  | "Wallet"
  | "Wand"
  | "Watch"
  | "Wifi"
  | "Wrench"
  | "Zap";

export interface NameValueObj {
  name: IconName;
  value: LucideIcon;
}
